### ISSUE TITLE
[RoleManagement] Cannot load cog

### ISSUE THREAD

**Issue by designbyadrian** [mikeshardmind/SinbadCogs#150]
`!load rolemanagement`

`Failed to load package rolemanagement. Check your console or logs for details.`

```
Jun 17 10:01:00 geraldo redbot[6991]: [17/06/2019 10:01] ERROR core_commands _load 108: Package loading failed
Jun 17 10:01:00 geraldo redbot[6991]: Traceback (most recent call last):
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/lib/python3.6/site-packages/redbot/core/core_commands.py", line 104, in _load
Jun 17 10:01:00 geraldo redbot[6991]:     await bot.load_extension(spec)
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/lib/python3.6/site-packages/redbot/core/bot.py", line 233, in load_extension
Jun 17 10:01:00 geraldo redbot[6991]:     lib = spec.loader.load_module()
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap_external>", line 399, in _check_name_wrapper
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap_external>", line 823, in load_module
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap_external>", line 682, in load_module
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap>", line 265, in _load_module_shim
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap>", line 684, in _load
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap_external>", line 678, in exec_module
Jun 17 10:01:00 geraldo redbot[6991]:   File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/rolemanagement/__init__.py", line 1
Jun 17 10:01:00 geraldo redbot[6991]:     from .core import RoleManagement
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/rolemanagement/core.py", line 11, i
Jun 17 10:01:00 geraldo redbot[6991]:     from .events import EventMixin
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/rolemanagement/events.py", line 9, 
Jun 17 10:01:00 geraldo redbot[6991]:     class EventMixin(MixinMeta):
Jun 17 10:01:00 geraldo redbot[6991]:   File "/home/designbyadrian/.local/share/Red-DiscordBot/cogs/CogManager/cogs/rolemanagement/events.py", line 10,
Jun 17 10:01:00 geraldo redbot[6991]:     @commands.Cog.listener()
Jun 17 10:01:00 geraldo redbot[6991]: AttributeError: type object 'Cog' has no attribute 'listener'
```

Updated both Red and the cog today.

**Comment by mikeshardmind** [comment]
Your bot is running on python3.6 and is not actually up to date (the latest version of Red requires python3.7)
