### ISSUE TITLE
[RoomTools] Game Room doesn't work

### ISSUE THREAD

**Issue by PhasecoreX** [mikeshardmind/SinbadCogs#171]
If an autoroom is set to be a game room, this error happens in the console:

```
Ignoring exception in on_voice_state_update                        
Traceback (most recent call last):                                 
  File "/data/venv/lib/python3.7/site-packages/discord/client.py", line 270, in _run_event
    await coro(*args, **kwargs)
  File "/data/cogs/CogManager/cogs/roomtools/autorooms.py", line 68, in on_voice_state_update_ar
    await self.generate_room_for(who=member, source=after.channel) 
  File "/data/cogs/CogManager/cogs/roomtools/autorooms.py", line 125, in generate_room_for
    if cname is None:
UnboundLocalError: local variable 'cname' referenced before assignment
```

Looks like you need to indent that if statement, or maybe define `cname = None` somewhere above it in scope.

**Comment by mikeshardmind** [comment]
Fixed in 26c6822
