### ISSUE TITLE
Cant update from this repo

### ISSUE THREAD

**Issue by urbels** [mikeshardmind/SinbadCogs#198]
**Describe the bug**
I can update every repo except thist one. Error:

[2020-01-27 16:53:25] [ERROR] red: Exception in command 'cog updateallfromrepos'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 890, in _cog_updateallfromrepos
    await self._cog_update_logic(ctx, repos=repos)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 970, in _cog_update_logic
    cogs_to_update, libs_to_update = await self._available_updates(cogs_to_check)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 306, in _available_updates
    modified = await repo.get_modified_modules(old_hash, repo.commit)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/repo_manager.py", line 382, in get_modified_modules
    for status in await self._get_file_update_statuses(old_rev, new_rev):
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/repo_manager.py", line 261, in _get_file_update_statuses
    raise errors.GitDiffError(
redbot.cogs.downloader.errors.GitDiffError: Git command failed: ['git', '-C', '/home/bots/.local/share/Red-DiscordBot/cogs/RepoManager/repos/sinbad', 'diff-tree', '--no-commit-id', '--name-status', '-r', '-z', '--line-prefix=\t', '177f12a860afa9b2bdbbe69ae11db1184a7feaf7', '85181532017432c1c853c6c1e956574e9416e76c']
Error message: Git diff failed for repo at path: /home/bots/.local/share/Red-DiscordBot/cogs/RepoManager/repos/sinbad

**Debug info**
Debug Info for Red
Red version
3.3.0
Python version
3.8.1 (64bit)
Discord.py version
1.3.1
Pip version
20.0.2
System arch
x86_64
User
bots
OS version
Ubuntu 16.04
Python executable
/usr/bin/python3.8

**Comment by mikeshardmind** [comment]
Appears to be an issue with your git version. Is that the full log?

**Comment by jack1142** [comment]
@urbels There *should* be another (most likely long) error right above the one you sent.

**Comment by urbels** [comment]
Full log:
[2020-01-28 10:04:35] [ERROR] red.downloader: usage: git diff-tree [--stdin] [-m] [-c] [--cc] [-s] [-v] [--pretty] [-t] [-r] [--root] [<common-diff-options>] <tree-ish> [<tree-ish>] [<path>...]
  -r            diff recursively
  --root        include the initial commit as diff against /dev/null

common diff options:
  -z            output diff-raw with lines terminated with NUL.
  -p            output patch format.
  -u            synonym for -p.
  --patch-with-raw
                output both a patch and the diff-raw format.
  --stat        show diffstat instead of patch.
  --numstat     show numeric diffstat instead of patch.
  --patch-with-stat
                output a patch and prepend its diffstat.
  --name-only   show only names of changed files.
  --name-status show names and status of changed files.
  --full-index  show full object name on index lines.
  --abbrev=<n>  abbreviate object names in diff-tree header and diff-raw.
  -R            swap input file pairs.
  -B            detect complete rewrites.
  -M            detect renames.
  -C            detect copies.
  --find-copies-harder
                try unchanged files as candidate for copy detection.
  -l<n>         limit rename attempts up to <n> paths.
  -O<file>      reorder diffs according to the <file>.
  -S<string>    find filepair whose only one side contains the string.
  --pickaxe-all
                show all files diff when -S is used and hit is found.
  -a  --text    treat all files as text.
[2020-01-28 10:04:35] [ERROR] red: Exception in command 'cog updateallfromrepos'
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/dist-packages/discord/ext/commands/core.py", line 83, in wrapped
    ret = await coro(*args, **kwargs)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 890, in _cog_updateallfromrepos
    await self._cog_update_logic(ctx, repos=repos)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 970, in _cog_update_logic
    cogs_to_update, libs_to_update = await self._available_updates(cogs_to_check)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/downloader.py", line 306, in _available_updates
    modified = await repo.get_modified_modules(old_hash, repo.commit)
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/repo_manager.py", line 382, in get_modified_modules
    for status in await self._get_file_update_statuses(old_rev, new_rev):
  File "/usr/local/lib/python3.8/dist-packages/redbot/cogs/downloader/repo_manager.py", line 261, in _get_file_update_statuses
    raise errors.GitDiffError(
redbot.cogs.downloader.errors.GitDiffError: Git command failed: ['git', '-C', '/home/bots/.local/share/Red-DiscordBot/cogs/RepoManager/repos/sinbad', 'diff-tree', '--no-commit-id', '--name-status', '-r', '-z', '--line-prefix=\t', '177f12a860afa9b2bdbbe69ae11db1184a7feaf7', '85181532017432c1c853c6c1e956574e9416e76c']
Error message: Git diff failed for repo at path: /home/bots/.local/share/Red-DiscordBot/cogs/RepoManager/repos/sinbad

Should I just try to readd this repo?

**Comment by jack1142** [comment]
Nope, this isn't issue with the repo, but with outdated git version. Red requires Git 2.11+ to work properly, to upgrade it use these commands:
```
sudo add-apt-repository -yu ppa:git-core/ppa
sudo apt -y upgrade git
```

**Comment by urbels** [comment]
It worked, thanks!
