### ISSUE TITLE
[v3 ModRemplacer] set' object has no attribute 'keys'

### ISSUE THREAD

**Issue by celi28** [mikeshardmind/SinbadCogs#99]
# Other bugs
### What were you trying to do?
`[p]mute server @anUserAccount` without specifying the mute time (expecting it to be infinite).

## What actually happened?
On discord channel: `Error in command 'mute server'. Check your console or logs for details.`
Traceback:
```python
Exception in command 'mute server'
Traceback (most recent call last):
  File "D:\Anaconda3\envs\discordbot\lib\site-packages\discord\ext\commands\core.py", line 61, in wrapped
    ret = await coro(*args, **kwargs)
  File "D:\DEV\Data\cogs\CogManager\cogs\modreplacer\mod.py", line 1062, in guild_mute
    guild_wide=True,
  File "D:\DEV\Data\cogs\CogManager\cogs\modreplacer\mod.py", line 1168, in process_mute
    await self.cancel_tempmute_expires(target, *successful.keys())
AttributeError: 'set' object has no attribute 'keys'
The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "D:\Anaconda3\envs\discordbot\lib\site-packages\discord\ext\commands\bot.py", line 899, in invoke
    await ctx.command.invoke(ctx)
  File "d:\dev\src\redbot\redbot\core\commands\commands.py", line 409, in invoke
    await super().invoke(ctx)
  File "D:\Anaconda3\envs\discordbot\lib\site-packages\discord\ext\commands\core.py", line 1024, in invoke
    await ctx.invoked_subcommand.invoke(ctx)
  File "D:\Anaconda3\envs\discordbot\lib\site-packages\discord\ext\commands\core.py", line 614, in invoke
    await injected(*ctx.args, **ctx.kwargs)
  File "D:\Anaconda3\envs\discordbot\lib\site-packages\discord\ext\commands\core.py", line 70, in wrapped
    raise CommandInvokeError(e) from e
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: AttributeError: 'set' object has no attribute 'keys'
```

## How can we reproduce this issue?

Install ModRemplacer from git repo V3 branch, and execute command.

**Comment by mikeshardmind** [comment]
:wave: hey, thanks for this. Unfortunately, I'm unlikely to have this fixed soon. I have this particular one hidden from V3's downloader for a reason right now. 

I should have time to get this fixed up a bit next week, but it is not a high priority. I'd suggest not using this for now, (and I'll be restructuring the branches next week as well so that the beta test stuff is on another branch, or possibly a different repo entirely).
